blog/api/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import views

from .views import (CategoryAPIView, TaskAPIDetailView, TaskAPIView,
                    TasksByCategoryView)

app_name = "blog-api"

urlpatterns = [
    path("task/", TaskAPIView.as_view(), name="task-api"),
    path("d/<int:id>/", TaskAPIDetailView.as_view(), name="task-detail-api"),
    path("category/", CategoryAPIView.as_view(), name="category-list-api"),
    path(
        "category/<slug:category_slug>/",
        TasksByCategoryView.as_view(),
        name="category-api",
    ),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="home"),
    path("deposit", views.DepositView.as_view(), name="deposit"),
    path("category/add", views.CategoryCreationView.as_view(), name="category-add"),
    path(
        "category/<slug:category_slug>/",
        views.CategoryElementsListView.as_view(),
        name="category-elements",
    ),
    path("add-element", views.TaskCreationView.as_view(), name="add-task"),
    path("edit-element/<int:id>/", views.TaskEditView.as_view(), name="edit-task"),
    path("export_excel/", views.ExportExcel.as_view(), name="export-excel"),
    path("export_csv/", views.csv_export, name="export-csv"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)

from blog.api.views import TaskViewSet

router = routers.DefaultRouter(trailing_slash=False)
router.register("task", TaskViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path(r"silk/", include("silk.urls", namespace="silk")),
    path("", include("blog.urls", namespace="blog")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/", include("blog.api.urls")),
    path("api-viewset/", include((router.urls, "api-viewset"))),
    path("account/", include("accounts.urls")),
]

blog/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.db import models
from django.template.defaultfilters import default, slugify
from django.utils.translation import gettext_lazy as _

from helpers.random_name_generator import RandomFileName


class TaskCustomManger(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(price_added=True)


class Category(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=70, null=False, unique=True)
    slug = models.SlugField(
        verbose_name=_("Category safe URL"), max_length=255, unique=True
    )

    objects = models.Manager

    class Meta:
        verbose_name = _("Category")
        verbose_name_plural = _("Categories")
        ordering = ["-name"]

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

    def __str__(self):
        return self.name


class Task(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    description = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True, editable=False)
    updated_at = models.DateTimeField(auto_now=True)
    price = models.DecimalField(max_length=6, max_digits=4, decimal_places=2)
    price_added = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    picture = models.ImageField(upload_to=RandomFileName("items_blog"), default=None)

    objects = TaskCustomManger()

    class Meta:
        ordering = ["-created_at"]

    def __str__(self):
        return self.name


class Deposit(models.Model):
    amount = models.DecimalField(
        default=0.00, null=False, decimal_places=2, max_digits=6
    )
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    assigned_at = models.DateField(auto_now=Task)

    objects = models.Manager()

    def __str__(self):
        return f"{self.user.username} has {self.amount}$"

blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, ValidationError

from .models import Category, Deposit, Task


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text="Optional.")
    last_name = forms.CharField(max_length=30, required=False, help_text="Optional.")
    email = forms.EmailField(
        max_length=254, help_text="Required. Inform a valid email address."
    )

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )


class DepositForm(forms.ModelForm):
    class Meta:
        model = Deposit
        fields = ("amount",)


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ("name",)


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ("name", "description", "price", "category")

    def clean_description(self):
        data = self.cleaned_data["description"]
        if len(data) <= 170:
            raise ValidationError("Description field must have more than 170 char.")

        return data

    def clean_price(self):
        price_data = self.cleaned_data["price"]
        try:
            user_deposit = Deposit.objects.get(user=self._user)
            if float(price_data) > float(user_deposit.amount):
                raise ValidationError("There is not enough money in your account")
            if price_data <= 0:
                raise ValidationError("price can not be negative")
        except ObjectDoesNotExist:
            raise ValidationError(
                "There is no an amount in your deposit please go and add some!!"
            )
        return price_data

    def __init__(self, *args, **kwargs):
        self._user = kwargs.pop("user", None)
        self._prev_url = kwargs.pop("prev_url", None)
        self._request = kwargs.pop("request", None)
        super().__init__(*args, **kwargs)
        if self._prev_url and "category" in self._prev_url:
            category_slug = self._prev_url.split("/")[-2]
            self.fields["category"].initial = Category.objects.get(slug=category_slug)
            self.fields["category"].queryset = None
        else:
            if self._user:
                self.fields["category"].queryset = Category.objects.filter(
                    user=self._user
                )
                self.fields["category"].initial = Category.objects.filter(
                    user=self._user
                )[0]

blog/api/views.py
from django.contrib.auth import models
from django.db.models import fields
from django.shortcuts import get_object_or_404
from filter_map.backends import FilterMapBackend
from rest_framework import (generics, mixins, permissions, serializers, status,
                            viewsets)
from rest_framework.authentication import (BasicAuthentication,
                                           SessionAuthentication,
                                           TokenAuthentication)
from rest_framework.response import Response
from rest_framework.viewsets import ModelViewSet

from accounts.api.permissions import IsOwner

from ..models import Category, Task
from .filters import BlogCustomFilter
from .pagination import BlogCustomPagination
from .serializers import CategorySerializer, TaskSerializers


class TaskAPIView(
    mixins.UpdateModelMixin,
    mixins.DestroyModelMixin,
    mixins.RetrieveModelMixin,
    generics.ListCreateAPIView,
):
    serializer_class = TaskSerializers
    queryset = Task.objects.all()
    pagination_class = BlogCustomPagination
    permission_classes = (permissions.IsAuthenticated,)
    filter_backends = (BlogCustomFilter, FilterMapBackend)
    filter_map = {
        "name": "name",
        "username": "user__username",
        "category": "category__name",
    }

    def get_object(self):
        request = self.request
        passed_id = request.GET.get("id", None)

        obj = None

        if passed_id is not None:
            obj = generics.get_object_or_404(self.queryset, id=passed_id)
            self.check_object_permissions(request, obj)

        return obj

    def create(self, request, *args, **kwargs):
        serializer = self.get_serializer(data=request.data)
        serializer.is_valid(raise_exception=True)
        self.perform_create(serializer)
        headers = self.get_success_headers(serializer.data)
        return Response(
            serializer.data, status=status.HTTP_201_CREATED, headers=headers
        )

    def put(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def patch(self, request, *args, **kwargs):
        return self.update(request, *args, **kwargs)

    def delete(self, request, *args, **kwargs):
        return self.destroy(request, *args, **kwargs)


class TaskAPIDetailView(mixins.CreateModelMixin, generics.RetrieveAPIView):
    serializer_class = TaskSerializers
    queryset = Task.objects.all()
    lookup_field = "id"

    def get(self, request, *args, **kwargs):
        return super().get(request, *args, **kwargs)


class TasksByCategoryView(generics.ListAPIView):
    serializer_class = TaskSerializers
    lookup_field = "category_slug"

    def get_queryset(self):
        url_slug = self.kwargs.get("category_slug")
        category_obj = Category.objects.get(slug=url_slug)
        qs = Task.objects.filter(category__in=[category_obj])
        return qs


class TaskViewSet(ModelViewSet):
    queryset = Task.objects.all()
    serializer_class = TaskSerializers
    lookup_field = "pk"


class CategoryAPIView(generics.ListAPIView):
    serializer_class = CategorySerializer
    queryset = Category.objects.all()

blog/views.py
import uuid
import csv

import xlwt
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import ObjectDoesNotExist
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect
from django.urls import reverse_lazy
from django.views.generic import FormView, ListView, TemplateView, View
from silk.profiling.profiler import silk_profile

from blog.models import *
from .utils import export_csv

from .forms import CategoryForm, DepositForm, TaskForm


class ExportExcel(View):
    model = Task

    def get(self, request, *args, **kwargs):
        return self.extract_excel()

    def get_queryset(self):
        prev_url = self.request.META.get("HTTP_REFERER")
        session_ids = self.request.session["query_ids"]

        if "category" in prev_url:
            category_slug = prev_url.split("/")[-2]
            return self.model.objects.filter(
                category__in=[Category.objects.get(slug=category_slug)]
            )

        if session_ids:
            return self.model.objects.filter(id__in=session_ids)
        self.request.session["query_ids"] = None

        return self.model.objects.filter(user=self.request.user)

    def extract_excel(self):
        response = HttpResponse(content_type="application/ms-excel")
        response["Content-Disposition"] = f"attachment; filename={uuid.uuid4()}.xls"

        wb = xlwt.Workbook(encoding="utf-8")
        ws = wb.add_sheet("django-try")

        row_num = 0
        font_style = xlwt.XFStyle()
        font_style.font.FAMILY_MODERN = True
        qs = self.get_queryset()

        columns = [
            "task_id",
            "user_id",
            "task_name",
            "description",
            "price",
            "category",
            "purchased_at",
        ]
        for col_num in range(len(columns)):
            ws.write(row_num, col_num, columns[col_num], font_style)

        rows = list(
            qs.values_list(
                "id", "user", "name", "description", "price", "category", "created_at"
            )
        )
        for row in rows:
            row_num += 1
            for col_num in range(len(row)):
                ws.write(row_num, col_num, str(row[col_num]), font_style)

        wb.save(response)
        return response


class IndexView(LoginRequiredMixin, ListView):
    template_name = "blog/home.html"
    model = Task
    paginate_by = 7
    context_object_name = "elements"

    @silk_profile(name="View Index Page")
    def get(self, request, *args, **kwargs):
        self.check_deposit(request)
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        try:
            context["deposit"] = Deposit.objects.get(user=self.request.user)
            context["categories"] = Category.objects.filter(user=self.request.user)

            # save the elements ids in request session to be used in excel extraction
            self.request.session["query_ids"] = list(
                context["elements"].values_list("id", flat=True)
            )
        except ObjectDoesNotExist as e:
            context["deposit"] = Deposit.objects.create(
                amount=0.00, user=self.request.user
            )
            context["elements"] = None
            context["categories"] = None
        return context

    def get_queryset(self):
        return self.model.objects.filter(user=self.request.user)

    def check_deposit(self, request):
        user_elements = self.model.objects.filter(user=request.user)
        user_deposit = Deposit.objects.filter(user=request.user)

        if user_deposit.exists():
            user_deposit = user_deposit[0]
            for element in user_elements:
                if not element.price_added:
                    user_deposit.amount = float(user_deposit.amount) - float(
                        element.price
                    )
                    element.price_added = True
                    element.save()
                    user_deposit.save()


class DepositView(LoginRequiredMixin, FormView):
    form_class = DepositForm
    template_name = "blog/deposit.html"

    def form_valid(self, form):
        form.save()
        return redirect("blog:home")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = Deposit.objects.get(user=self.request.user)
        return kwargs


class CategoryElementsListView(LoginRequiredMixin, ListView):
    model = Task
    template_name = "blog/home.html"
    context_object_name = "elements"
    paginate_by = 4

    def get_queryset(self):
        return self.model.objects.filter(
            category__in=[Category.objects.get(slug=self.kwargs["category_slug"])]
        )


class CategoryCreationView(LoginRequiredMixin, FormView):
    form_class = CategoryForm
    template_name = "blog/category.html"

    def form_valid(self, form):
        category = form.save(commit=False)
        category.user = self.request.user
        category.save()
        return redirect("blog:home")


class TaskCreationView(LoginRequiredMixin, FormView):
    form_class = TaskForm
    template_name = "blog/element.html"

    def form_valid(self, form):
        task = form.save(commit=False)
        task.user = self.request.user
        task.save()
        return redirect("blog:home")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        kwargs["request"] = self.request
        return kwargs


class TaskEditView(LoginRequiredMixin, FormView):
    form_class = TaskForm
    template_name = "blog/element.html"
    model = Task
    success_url = reverse_lazy("blog:home")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["instance"] = self.model.objects.get(id=self.kwargs["id"])
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        # check if the user changed the price of the element and subtract from the deposit
        deposit = Deposit.objects.get(user=self.request.user)
        task_obj = self.model.objects.get(id=self.kwargs["id"])
        if float(task_obj.price) != float(form.cleaned_data["price"]):
            deposit.amount = (float(deposit.amount) + float(task_obj.price)) - float(
                form.cleaned_data["price"]
            )
            deposit.save()

        # save task instance
        form.save()
        return HttpResponseRedirect(self.success_url)


def csv_export(request):
    prev_url = request.META.get("HTTP_REFERER")
    session_ids = request.session.get("query_ids")
    queryset = None

    if session_ids:
        queryset = Task.objects.filter(id__in=session_ids)
        request.session['query_ids'] = None

    if 'category' in prev_url:
        print(prev_url)
        category_slug = prev_url.split("/")[-2]
        queryset = Task.objects.filter(
            category__in=[Category.objects.get(slug=category_slug)]
        )

    data = export_csv(request, queryset=queryset)
    response = HttpResponse(data, content_type='text/csv')

    return response

templates/blog/category.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <h1>Add Category</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Add category</button>
    </form>
</div>
{% endblock %}

templates/blog/deposit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <h1>Deposit</h1>
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Add to your savings</button>
    </form>
</div>
{% endblock %}

templates/blog/element.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary" type="submit">Add element</button>
    </form>
</div>
{% endblock %}

templates/blog/home.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="container" style="margin-top: 50px;">
    <div class="col" style="margin-bottom: 10px;">
        <div class="row">
            {% if not request.path|string == '/'|string %}
            <a href="{% url 'blog:add-task' %}" class="text-reset text-decoration-none" role="button" style="max-width: 560px; position: relative; left: 25%; margin-bottom: 10px;">
                <div class="card mb-3 h-100" style="border: dashed 2px #ccc;">
                    <div class="row g-0 h-100">
                        <div class="col-12" style="min-height:100px">
                            <div class="card-body text-center position-absolute top-50 start-50 translate-middle">
                                <svg style="color:#ccc;" xmlns="http://www.w3.org/2000/svg" width="60" height="60"
                                    fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                                    <path
                                        d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                                </svg>
                                <h1 class="h5">Add Element</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {% else %}
            <a href="{% url 'blog:add-task' %}" class="text-reset text-decoration-none" role="button" style="max-width: 360px;">
                <div class="card mb-3 h-100" style="border: dashed 2px #ccc;">
                    <div class="row g-0 h-100">
                        <div class="col-12" style="min-height:100px">
                            <div class="card-body text-center position-absolute top-50 start-50 translate-middle">
                                <svg style="color:#ccc;" xmlns="http://www.w3.org/2000/svg" width="60" height="60"
                                    fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                                    <path
                                        d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                                </svg>
                                <h1 class="h5">Add Element</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <a href="{% url 'blog:deposit' %}" class="text-reset text-decoration-none" role="button" style="max-width: 360px;">
                <div class="card mb-3 h-100" style="border: dashed 2px #ccc;">
                    <div class="row g-0 h-100">
                        <div class="col-12" style="min-height:100px">
                            <div class="card-body text-center position-absolute top-50 start-50 translate-middle">
                                <svg style="color:#ccc;" xmlns="http://www.w3.org/2000/svg" width="60" height="60"
                                    fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                                    <path d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                                </svg>
                                <h1 class="h5">Deposit</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            <a href="{% url 'blog:category-add' %}" class="text-reset text-decoration-none" role="button" style="max-width: 360px;">
                <div class="card mb-3 h-100" style="border: dashed 2px #ccc;">
                    <div class="row g-0 h-100">
                        <div class="col-12" style="min-height:100px">
                            <div class="card-body text-center position-absolute top-50 start-50 translate-middle">
                                <svg style="color:#ccc;" xmlns="http://www.w3.org/2000/svg" width="60" height="60"
                                    fill="currentColor" class="bi bi-plus" viewBox="0 0 16 16">
                                    <path
                                        d="M8 4a.5.5 0 0 1 .5.5v3h3a.5.5 0 0 1 0 1h-3v3a.5.5 0 0 1-1 0v-3h-3a.5.5 0 0 1 0-1h3v-3A.5.5 0 0 1 8 4z" />
                                </svg>
                                <h1 class="h5">Add Category</h1>
                            </div>
                        </div>
                    </div>
                </div>
            </a>
            {% endif %}
        </div>
    </div>
    <table class="table table-dark table-hover">
        <thead>
            <tr>
<!--                <th scope="col">#</th>-->
                <th scope="col">name</th>
                <th scope="col">description</th>
                <th scope="col">purchased at</th>
                <th scope="col">price</th>
                <th scope="col">category</th>
            </tr>
        </thead>
        <tbody>
        {% if not request.path|string == '/'|string %}
        {% for element in elements %}
        <tr>
            <td><a href="{% url 'blog:edit-task' element.id %}">{{element.name}}</a></td>
            <td>{{element.description|upper}}</td>
            <td>{{element.created_at}}</td>
            <td>{{element.price}}</td>
            <td style="color: purple;">{{element.category.name}}</td>
        </tr>
        {% endfor %}
        {% else %}
            {% if elements %}
            {% for element in elements %}
            <tr>
                <td><a href="{% url 'blog:edit-task' element.id %}">{{element.name}}</a></td>
                {% if element.description|length > 100 %}
                <td>{{element.description|lower|slice:":100"}}...</td>
                {% else%}
                <td>{{element.description|lower}}</td>
                {% endif %}
                <td>{{element.created_at}}</td>
                <td>{{element.price}}</td>
                <td><a href="{% url 'blog:category-elements' element.category.slug %}">{{element.category.name}}</a></td>
            </tr>
            {% endfor %}
            {% else %}
                <tr>
                    <th scope="row">-</th>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                    <td>-</td>
                </tr>
            {% endif %}
        {% endif %}
        </tbody>
    </table>
    <div class="pagination">
        <span class="step-links">
            {% if page_obj.has_previous %}
<!--                <a href="?page=1">&laquo; first</a>-->
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
<!--                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>-->
            {% endif %}
        </span>
    </div>
    <div class="row">
        <div class="col-4">
            <a class="btn btn-success" href="{% url 'blog:export-excel' %}">Extract to Excel</a>
            <a class="btn btn-secondary" href="{% url 'blog:export-csv' %}" role="button">Extract to CSV</a>
        </div>
    </div>
</div>
{% endblock %}