accounts/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path

from . import views
from .forms import UserLoginForm

app_name = "account"

urlpatterns = [
    path(
        "login/",
        views.LogInView.as_view(),
        name="login",
    ),
    path("signup/", views.SignUpView.as_view(), name="signup"),
    path(
        "logout/",
        auth_views.LogoutView.as_view(next_page="/account/login/"),
        name="logout",
    ),
]

blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.IndexView.as_view(), name="home"),
    path("deposit", views.DepositView.as_view(), name="deposit"),
    path("category/add", views.CategoryCreationView.as_view(), name="category-add"),
    path(
        "category/<slug:category_slug>/",
        views.CategoryElementsListView.as_view(),
        name="category-elements",
    ),
    path("add-element", views.TaskCreationView.as_view(), name="add-task"),
    path("edit-element/<int:id>/", views.TaskEditView.as_view(), name="edit-task"),
    path("export_excel/", views.ExportExcel.as_view(), name="export-excel"),
    path("export_csv/", views.csv_export, name="export-csv"),
]

core/urls.py
from django.contrib import admin
from django.urls import include, path
from rest_framework import routers
from rest_framework_simplejwt.views import (TokenObtainPairView,
                                            TokenRefreshView)

from blog.api.views import TaskViewSet

router = routers.DefaultRouter(trailing_slash=False)
router.register("task", TaskViewSet)

urlpatterns = [
    path("admin/", admin.site.urls),
    path(r"silk/", include("silk.urls", namespace="silk")),
    path("", include("blog.urls", namespace="blog")),
    path("api/token/", TokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("api/token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("api/", include("blog.api.urls")),
    path("api-viewset/", include((router.urls, "api-viewset"))),
    path("account/", include("accounts.urls")),
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <title>Payment handler</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'blog/css/blog.css' %}">
</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" style="">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'blog:home' %}">Payment handler</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
                aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarScroll">
                <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
                    <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{% url 'blog:home' %}">Home</a>
                    </li>
                </ul>
                {% if request.user.is_authenticated %}
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <a class="btn btn-primary nav-item" href="{% url "account:logout" %}" role="button">Log out</a>
                </ul>
                {% else %}
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <a class="btn btn-primary nav-item" href="{% url "account:signup" %}" role="button">Sign up</a>
                </ul>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    <a class="btn btn-primary nav-item" href="{% url "account:login" %}" role="button">Log in</a>
                </ul>
                {% endif %}
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if deposit %}
                    <li class="nav-item deposit_border"><a href="{% url 'blog:deposit' %}" class="deposit_url">Total
                            Deposit: {{ deposit.amount }}$</a></li>
                    {% else %}
                    <li class="nav-item deposit_border"><a href="#" class="deposit_url">Total Deposit: 0.00$</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    {% block content %}{% endblock %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
    </script>
    <script>
        delete window.document.referrer;
        window.document.__defineGetter__('referrer', function () {
            return "yoururl.com";
        });
    </script>
</body>

</html>